#  Copyright (c) 2021. by Roman N. Krivov a.k.a. Eochaid Bres Drow

VM_STATUS_RUNNING = 'running'
VM_STATUS_PAUSED = 'paused'
VM_STATUS_STOPPED = 'stopped'
VM_STATUS_SUSPENDED = 'suspended'

VM_SNAPSHOT_POWER_ON = 'poweron'
VM_SNAPSHOT_POWER_OFF = 'poweroff'
VM_SNAPSHOT_SUSPEND = 'suspend'

VM_TYPE_NORMAL = 'PVM'
VM_TYPE_ARCHIVED = 'PVMZ'
VM_TYPE_PACKED = 'PVMP'

VM_SNAPSHOT_COUNT = 2
VM_SNAPSHOT_DAYS_COUNT = 14
